### ISSUE TITLE
Datei vom 26.02.2021 fehlerhaft (doppelte Daten)

### ISSUE THREAD

**Issue by real-iceman** [micb25/RKI_COVID19_DATA#3]
Erst mal vielen Dank für die Zusammenstellung der RKI-Daten!

Gestern hat das RKI leider zunächst eine fehlerhafte Datei veröffentlich, die später korrigiert wurde. Anscheinend waren die Daten doppelt, erkennbar auch an der Dateigröße.

Im Repository ist leider noch die falsche Datei. Die korrekte Version kann ich ggf. zur Verfügung stellen.

**Comment by micb25** [comment]
Vielen Dank für das Melden! Ich hatte mir gestern zur Sicherheit schon manuell die korrigierte Datei heruntergeladen. Ist jetzt aktualisiert. :-)
