### ISSUE TITLE
Falscher Datenstand in RKI-Datei vom 14.03.2021

### ISSUE THREAD

**Issue by real-iceman** [micb25/RKI_COVID19_DATA#4]
Gestern (14.03.2021) standen die RKI-Daten leider erst sehr spät zur Verfügung. Die Datei im Repository enthält daher noch die Daten vom Vortag (13.03.).

Die korrekte Datei kann ich bei Bedarf zur Verfügung stellen.

**Comment by micb25** [comment]
Vielen Dank für das erneute Melden! Ich hatte es heute Vormittag bereits gesehen, dass es erneut zu Problemen mit dem Dashboard kam. Zumindest werden diese aber zeitnah kommuniziert und gelöst. Die korrekte CSV-Datei ist jetzt im Repo eingespielt. :-)
